// This file is auto-generated by tools/cmd/genoptions/main.go. DO NOT EDIT

package dataurl

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestOptionIdent(t *testing.T) {
	require.Equal(t, "WithBase64Encoding", identBase64Encoding{}.String())
	require.Equal(t, "WithMediaType", identMediaType{}.String())
	require.Equal(t, "WithMediaTypeParams", identMediaTypeParams{}.String())
}
